CREATE TABLE "bills" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subcategory_id" int NOT NULL,
  "account_id" int NOT NULL,
  "amount" decimal(12,2) NOT NULL,
  "description" text,
  "occurred_at" timestamp NOT NULL DEFAULT (now()),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "bills_category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "bills_subcategory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "mindless_spending" bool NOT NULL DEFAULT (now())
);

CREATE TABLE "bills_account" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

ALTER TABLE "bills" ADD FOREIGN KEY ("subcategory_id") REFERENCES "bills_subcategory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bills" ADD FOREIGN KEY ("account_id") REFERENCES "bills_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bills_subcategory" ADD FOREIGN KEY ("category_id") REFERENCES "bills_category" ("id") DEFERRABLE INITIALLY IMMEDIATE;